Update main.yml to install Terraform if not present

diff --git a/ansible/roles/terraform/tasks/main.yml b/ansible/roles/terraform/tasks/main.yml
--- a/ansible/roles/terraform/tasks/main.yml
+++ b/ansible/roles/terraform/tasks/main.yml
@@ -1,8 +1,14 @@
----
-- name: Install Terraform
-  shell: |
-    TERRAFORM_VERSION=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//')
-    wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
-    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
-    sudo mv terraform /usr/local/bin/
-    rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
+# Check if Terraform is installed
+if ! command -v terraform &> /dev/null
+then
+    echo "Terraform not found! Installing..."
+    # Commands to install Terraform
+    # For example, on Ubuntu:
+    sudo apt-get update
+    sudo apt-get install -y gnupg software-properties-common curl
+    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
+    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+    sudo apt-get update
+    sudo apt-get install terraform
+else
+    echo "Terraform is already installed."i
